[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for the frontend
[build.environment]
  NODE_VERSION = "18"
